apiVersion: extension/v1beta1
kind: Ingree
metadata:
  name: ingress-service
  annotation:
    kubernetes.io/ingress.class: nginx #to create a nginx controller
    nginx.ingress.kubernetes.io/rewite-target: / #removes the additional routes from the request like '/api'
spec:
  rules:
      - http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000

