apiVersion: v1
kind: Service
metadata: #info about this service
  name: <cluster-ip-service name>
spec:
  type: ClusterIP
  selector: #details about target
    <key> : <value>
  ports:
    - port: <input port> #other -> this
      targetPort: <outward port> #this -> other including outside world