apiVersion: extension/v1beta1
kind: Ingree
metadata:
  name: myapp-name
  annotation: #higher level config if any
    kubernetes.io/ingress.class: nginx #to create a nginx controller
    nginx.ingress.kubernetes.io/rewite-target: / #removes the additional routes from the request like '/api'
spec:
  rules:
      - http:
        paths:
          - path: <route 1>
            backend:
              serviceName: <service name from meta data in the service file>
              servicePort: <Port property value from sercive.conf file> #this is the port exposed by the container

          - path: <route 2>
            backend:
              serviceName: <service name from meta data in the service file>
              servicePort: <Port property value from sercive.conf file> #this is the port exposed by the container

